### ISSUE TITLE
readcount to FPKM

### ISSUE THREAD

**Issue by alibumizj** [zhangyuqing/ComBat-seq#10]
Hi,
Can I use  readcount from ComBat-seq  to calculate FPKM or TPM ?

Best wishes

**Comment by zhangyuqing** [comment]
Hi @alibumizj, interesting question. I believe for TPM you can, there has been discussions about that. Perhaps @wevanjohnson can provide more details?

**Comment by wevanjohnson** [comment]
Yes, you can use the ComBat-Seq adjusted counts for FPKM or TPM
