### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by zckoo007** [zhangyuqing/ComBat-seq#11]
> devtools::install_github("zhangyuqing/sva-devel")
Downloading GitHub repo zhangyuqing/sva-devel@master
trying URL 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/bin/windows/Rtools/Rtools35.exe'
Content type 'application/octet-stream' length 108622512 bytes (103.6 MB)
downloaded 40.5 MB

Error: Failed to install 'unknown package' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
In addition: Warning message:
In utils::download.file("https://mirrors.tuna.tsinghua.edu.cn/CRAN/bin/windows/Rtools/Rtools35.exe",  :
  downloaded length 42446848 != reported length 108622512

**Comment by zhangyuqing** [comment]
Hi @zckoo007, this does not look like an issue with combat-seq. Instead, when using devtools, you need to install Rtools first, which looks like the problem you ran into. https://cran.r-project.org/bin/windows/Rtools/
