### ISSUE TITLE
ComBat-Seq and pseudobulk counts

### ISSUE THREAD

**Issue by AmelZulji** [zhangyuqing/ComBat-seq#12]
Thank you for this major improvement, Yuqing! 

Since you mentioned in the previous issues that it is valid to use corrected values as input for DESeq2, I am wondering can the ComBat-seq be used for correcting pseudobulk-counts from single-cell data followed by DESeq2 DGE analysis? 

In addition, if experimental design includes control and condition samples processed in multiple batches, is separate batch correction (i.e. separate batch correction of control samples + separate batch correction of  condition samples, followed by merging matrices) a valid approach? Or that can be handled by specifying groups?

Thank you in advance for your help!

Kind regards,
Amel Zulji

**Comment by zhangyuqing** [comment]
Hi @AmelZulji, yes, you can use ComBat-seq to correct pseudobulk-counts. The control and condition samples can be handled by specifying groups in the parameters.

**Comment by AmelZulji** [comment]
Thank you very much, Yuqing!
