### ISSUE TITLE
combat-seq can set a reference batch like combat?

### ISSUE THREAD

**Issue by taojinsheng** [zhangyuqing/ComBat-seq#13]
Hi yuqing,

I know combat can set a reference batch.I wonder whether combat-seq can also set a reference batch by modifying some code.If yes,is it easy to implement or non-trivial to do so? I am looking forward to your reply.

Best,

Jinsheng

**Comment by zhangyuqing** [comment]
Hi @taojinsheng, great question, thanks. We talked about adding a reference batch option to ComBat-Seq, which in my opinion is not difficult to implement. Unfortunately I do not have the bandwidth to do that for now, and it is not available in the function yet.
