### ISSUE TITLE
Question concerning further analysis 

### ISSUE THREAD

**Issue by JJBio** [zhangyuqing/ComBat-seq#3]
Thank you for implementing the ComBat_seq function. I am eager to try it out. 
I have a question concerning the further analysis workflow. Can I just adjust the counts and then continue with standard workflows? Hence filter the low expressed genes (or should that already be done before batch correcting?), normalising e.g. TMM and then converting to logCPM or voom transformation and so on? 
How would the workflow/input exactly differ between ComBat_seq and ComBat? 
Thanks so much!

**Comment by zhangyuqing** [comment]
Hi @JJBio, thank you for trying ComBat-Seq! T

hough I think the workflow you propose will not generate errors, ComBat-Seq is more suitable for downstream analysis software that requires untransformed counts (edgeR or DESeq2, for example). 

ComBat is more suitable for Gaussian distributed data (microarray, log transformed counts for RNASeq), while ComBat-Seq is more suitable for count data with highly skewed distribution (raw count for RNA-Seq). 

Filtering low expressed genes is recommended before using ComBat-Seq, although the latest version should identify genes with only 0s in any batch, and keep them unchanged.

**Comment by JJBio** [comment]
Hi @zhangyuqing, thanks so much for your quick and helpful reply!

I have raw counts but the analysis is based on logCPM, voom transformed or RPKM data. Also, differential analysis is not my main goal. But I have a profound batch effect I need to correct for.

Which workflow would you recommend in this case? 
raw counts -> filtering -> ComBat-Seq -> TMM -> logCPM/RPKM/voom
or 
raw counts -> filtering -> TMM -> logCPM/RPKM/voom -> ComBat

Thanks so much for your input!

**Comment by zhangyuqing** [comment]
I recommend analyzing the distribution of your data and potential reason for batch effect to choose the better workflow.
