### ISSUE TITLE
ComBat_seq cannot be found

### ISSUE THREAD

**Issue by Zepeng-Mu** [zhangyuqing/ComBat-seq#5]
Hi, I installed the package from GitHub repo sva-devel. I can see the document page of `ComBat_seq` but when I try to run the function, I got "could not find function "ComBat_seq".

**Comment by mestato** [comment]
Did you load the library? After installing the devel version, make sure you load/attach it:

`library("sva")`

**Comment by Zepeng-Mu** [comment]
I think I actually did. I could use the old version of `ComBat` for instance. Now I just clone the GitHub repo and use `source` to load `ComBat_seq` and it works.

**Comment by madhulika-EBI** [comment]
Hi, I am also not able to find ComBat_seq upon package installation. can you please make it available through Bioconductor SVA version also. Thanks

**Comment by PrincescaDorsaint** [comment]
Hi, I also cannot find the ComBat_seq function via "sva" package. Is this function no longer available?

**Comment by zhangyuqing** [comment]
@Zepeng-Mu @madhulika-EBI @PrincescaDorsaint ComBat-Seq is already available in the development version of Bioconductor, which I believe requires R > 4.0. https://www.bioconductor.org/packages/devel/bioc/html/sva.html 

If you do not want to update your R version to use devel Bioconductor, you can 1) wait until the next Bioconductor release, 2) clone the GitHub repo and use source to load ComBat_seq, as @Zepeng-Mu suggests, or 3) use the sva package on my github devtools::install_github("zhangyuqing/sva-devel").

With 3), make sure to remove the previous sva installed on your laptop: remove.packages("sva") before installing. After installation, check packageVersion("sva") to make sure it is version 3.35.2. This works on my laptop, and I'm able to find ComBat_seq function. If you still can't find it, there are suggested steps you can try to fix the issue: https://stackoverflow.com/questions/7027288/error-could-not-find-function-in-r

**Comment by Bithorax** [comment]
None of the options suggested works for me. Am I the only one having this issue?

**Comment by Zepeng-Mu** [comment]
I installed sva 3.38.0 from bioconductor and it has the `ComBat_seq` function, but you need R 4.0.0 to successfully install the package.

**Comment by Bithorax** [comment]
Apparently, I had an issue with the installation. Now working! Thanks!

**Comment by daixiaozhuan** [comment]
> I think I actually did. I could use the old version of `ComBat` for instance. Now I just clone the GitHub repo and use `source` to load `ComBat_seq` and it works.

How to use source to load it

**Comment by ShwetaCh** [comment]
@zhangyuqing 
Apologies to bother you on this, but I tried option3 to sva-devel since I didn't want to upgrade my R completely, it does not work for me. Is it broken at the source by any chance or do I need to do anything more at my end?

```
> devtools::install_github("zhangyuqing/sva-devel")
Downloading GitHub repo zhangyuqing/sva-devel@HEAD
sh: 1: /bin/gtar: not found
sh: 1: /bin/gtar: not found
Error: Failed to install 'sva' from GitHub:
  error in running command
In addition: Warning messages:
1: In system(cmd) : error in running command
2: In utils::untar(tarfile, ...) :
  ‘/bin/gtar -xf '/tmp/Rtmp7pld2E/file4a0e386a4721.tar.gz' -C '/tmp/Rtmp7pld2E/remotes4a0e2f329d74'’ returned error code 127
```

Update: I did it the source way

**Comment by ShwetaCh** [comment]
> How to use source to load it

@daixiaozhuan You can do it as below:
`git clone https://github.com/zhangyuqing/ComBat-seq.git `<-- on command prompt
`source("/home/user/testing/ComBat-seq/ComBat_seq.R")` <-- inside your R script
