### ISSUE TITLE
ComBat-seq + DESeq2

### ISSUE THREAD

**Issue by 14lwt1** [zhangyuqing/ComBat-seq#7]
Hi,
I am wondering if it is valid to input batch adjusted counts from ComBat-seq into DESeq2's standard workflow.
Thank you.

**Comment by zhangyuqing** [comment]
Hi @14lwt1, yes, it is valid to input combat-seq adjusted data into DESeq2.

**Comment by etaagen** [comment]
As a follow up question - if you input batch adjusted counts from ComBat_seq, you should drop `batch` in the DEseq2 design model? Thank you.

**Comment by alibumizj** [comment]
Hi,
DESeq2  workflow has considered  batch effects in group design ,should we need remove batch effects before DESeq2 difference analysis? 
Thank you
Best wishes

**Comment by PoisonAlien** [comment]
Same question here. Should we remove Batch as a covariate?

```r
adjusted <- ComBat_seq(counts = as.matrix(counts), batch = pdata$Batch)

dds = DESeq2::DESeqDataSetFromMatrix(countData = adjusted, colData = pdata, design = ~ Batch + Condition)
OR
dds = DESeq2::DESeqDataSetFromMatrix(countData = adjusted, colData = pdata, design = ~ Condition)

```

**Comment by zhangyuqing** [comment]
@alibumizj @PoisonAlien When considering batch effects in group design, it takes into account the mean differences across batch, not necessarily the variance differences. ComBat-Seq is designed to address both mean and variance batch effects. In theory, no, you do not need to include batch as a covariate any more. However, you can always try both and evaluate the results.
