### ISSUE TITLE
including more than one feature to be corrected

### ISSUE THREAD

**Issue by leonorrib** [zhangyuqing/ComBat-seq#8]
Hello, thank you for developing ComBat-seq. It is definitely useful. I would like to ask whether there is a way to use ComBat-seq to correct two different features. One feature would be the typical batch effect, and another would be to correct for different sample concentrations in the libraries.

Best,
Leonor

**Comment by zhangyuqing** [comment]
Hi @leonorrib, thanks for your comment, interesting question! ComBat-Seq is not designed to resolve sample concentration differences by itself. However, there may be ways to address it, for example, cluster samples based on sample concentrations, then treat the clusters as a type of "batch". This would require future research.
